(cl:defpackage baxter_control_mine-srv
  (:use )
  (:export
   "POSITIONCOMMANDMINE"
   "<POSITIONCOMMANDMINE-REQUEST>"
   "POSITIONCOMMANDMINE-REQUEST"
   "<POSITIONCOMMANDMINE-RESPONSE>"
   "POSITIONCOMMANDMINE-RESPONSE"
  ))

