(cl:defpackage baxter_control_mine-srv
  (:use )
  (:export
   "CALCULATEIK"
   "<CALCULATEIK-REQUEST>"
   "CALCULATEIK-REQUEST"
   "<CALCULATEIK-RESPONSE>"
   "CALCULATEIK-RESPONSE"
   "POSITIONCOMMANDMINE"
   "<POSITIONCOMMANDMINE-REQUEST>"
   "POSITIONCOMMANDMINE-REQUEST"
   "<POSITIONCOMMANDMINE-RESPONSE>"
   "POSITIONCOMMANDMINE-RESPONSE"
  ))

