// Generated by gencpp from file move_rt/ExecutingTrajectoryGoal.msg
// DO NOT EDIT!


#ifndef MOVE_RT_MESSAGE_EXECUTINGTRAJECTORYGOAL_H
#define MOVE_RT_MESSAGE_EXECUTINGTRAJECTORYGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_rt
{
template <class ContainerAllocator>
struct ExecutingTrajectoryGoal_
{
  typedef ExecutingTrajectoryGoal_<ContainerAllocator> Type;

  ExecutingTrajectoryGoal_()
    : trajectory_name()
    , ee_error_th(0.0)  {
    }
  ExecutingTrajectoryGoal_(const ContainerAllocator& _alloc)
    : trajectory_name(_alloc)
    , ee_error_th(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _trajectory_name_type;
  _trajectory_name_type trajectory_name;

   typedef double _ee_error_th_type;
  _ee_error_th_type ee_error_th;





  typedef boost::shared_ptr< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ExecutingTrajectoryGoal_

typedef ::move_rt::ExecutingTrajectoryGoal_<std::allocator<void> > ExecutingTrajectoryGoal;

typedef boost::shared_ptr< ::move_rt::ExecutingTrajectoryGoal > ExecutingTrajectoryGoalPtr;
typedef boost::shared_ptr< ::move_rt::ExecutingTrajectoryGoal const> ExecutingTrajectoryGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move_rt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'move_rt': ['/home/lar/ros/baxter_ws/devel/share/move_rt/msg', '/home/lar/ros/baxter_ws/devel/share/move_rt/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8f8c747702d98a2b465764ab182b654";
  }

  static const char* value(const ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8f8c747702d98a2ULL;
  static const uint64_t static_value2 = 0xb465764ab182b654ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_rt/ExecutingTrajectoryGoal";
  }

  static const char* value(const ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
string trajectory_name\n\
float64 ee_error_th  # Specify error threshold\n\
";
  }

  static const char* value(const ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectory_name);
      stream.next(m.ee_error_th);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecutingTrajectoryGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_rt::ExecutingTrajectoryGoal_<ContainerAllocator>& v)
  {
    s << indent << "trajectory_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.trajectory_name);
    s << indent << "ee_error_th: ";
    Printer<double>::stream(s, indent + "  ", v.ee_error_th);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_RT_MESSAGE_EXECUTINGTRAJECTORYGOAL_H
