// Generated by gencpp from file move_rt/ExecutingTrajectoryResult.msg
// DO NOT EDIT!


#ifndef MOVE_RT_MESSAGE_EXECUTINGTRAJECTORYRESULT_H
#define MOVE_RT_MESSAGE_EXECUTINGTRAJECTORYRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_rt
{
template <class ContainerAllocator>
struct ExecutingTrajectoryResult_
{
  typedef ExecutingTrajectoryResult_<ContainerAllocator> Type;

  ExecutingTrajectoryResult_()
    : error_code(0)  {
    }
  ExecutingTrajectoryResult_(const ContainerAllocator& _alloc)
    : error_code(0)  {
  (void)_alloc;
    }



   typedef int32_t _error_code_type;
  _error_code_type error_code;



  enum {
    SUCCESSFUL = 0,
    INVALID_GOAL = -1,
    INVALID_JOINTS = -2,
    OLD_HEADER_TIMESTAMP = -3,
    PATH_TOLERANCE_VIOLATED = -4,
    GOAL_TOLERANCE_VIOLATED = -5,
  };


  typedef boost::shared_ptr< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> const> ConstPtr;

}; // struct ExecutingTrajectoryResult_

typedef ::move_rt::ExecutingTrajectoryResult_<std::allocator<void> > ExecutingTrajectoryResult;

typedef boost::shared_ptr< ::move_rt::ExecutingTrajectoryResult > ExecutingTrajectoryResultPtr;
typedef boost::shared_ptr< ::move_rt::ExecutingTrajectoryResult const> ExecutingTrajectoryResultConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move_rt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'move_rt': ['/home/lar/ros/baxter_ws/devel/share/move_rt/msg', '/home/lar/ros/baxter_ws/devel/share/move_rt/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6243274b5d629dc838814109754410d5";
  }

  static const char* value(const ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6243274b5d629dc8ULL;
  static const uint64_t static_value2 = 0x38814109754410d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_rt/ExecutingTrajectoryResult";
  }

  static const char* value(const ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
int32 error_code\n\
int32 SUCCESSFUL = 0\n\
int32 INVALID_GOAL = -1\n\
int32 INVALID_JOINTS = -2\n\
int32 OLD_HEADER_TIMESTAMP = -3\n\
int32 PATH_TOLERANCE_VIOLATED = -4\n\
int32 GOAL_TOLERANCE_VIOLATED = -5\n\
";
  }

  static const char* value(const ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecutingTrajectoryResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_rt::ExecutingTrajectoryResult_<ContainerAllocator>& v)
  {
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_RT_MESSAGE_EXECUTINGTRAJECTORYRESULT_H
