// Generated by gencpp from file move_rt/TaskParamUpdate.msg
// DO NOT EDIT!


#ifndef MOVE_RT_MESSAGE_TASKPARAMUPDATE_H
#define MOVE_RT_MESSAGE_TASKPARAMUPDATE_H

#include <ros/service_traits.h>


#include <move_rt/TaskParamUpdateRequest.h>
#include <move_rt/TaskParamUpdateResponse.h>


namespace move_rt
{

struct TaskParamUpdate
{

typedef TaskParamUpdateRequest Request;
typedef TaskParamUpdateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TaskParamUpdate
} // namespace move_rt


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_rt::TaskParamUpdate > {
  static const char* value()
  {
    return "ae13d2079549ecafaa66d49d24c80c49";
  }

  static const char* value(const ::move_rt::TaskParamUpdate&) { return value(); }
};

template<>
struct DataType< ::move_rt::TaskParamUpdate > {
  static const char* value()
  {
    return "move_rt/TaskParamUpdate";
  }

  static const char* value(const ::move_rt::TaskParamUpdate&) { return value(); }
};


// service_traits::MD5Sum< ::move_rt::TaskParamUpdateRequest> should match 
// service_traits::MD5Sum< ::move_rt::TaskParamUpdate > 
template<>
struct MD5Sum< ::move_rt::TaskParamUpdateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_rt::TaskParamUpdate >::value();
  }
  static const char* value(const ::move_rt::TaskParamUpdateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_rt::TaskParamUpdateRequest> should match 
// service_traits::DataType< ::move_rt::TaskParamUpdate > 
template<>
struct DataType< ::move_rt::TaskParamUpdateRequest>
{
  static const char* value()
  {
    return DataType< ::move_rt::TaskParamUpdate >::value();
  }
  static const char* value(const ::move_rt::TaskParamUpdateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_rt::TaskParamUpdateResponse> should match 
// service_traits::MD5Sum< ::move_rt::TaskParamUpdate > 
template<>
struct MD5Sum< ::move_rt::TaskParamUpdateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_rt::TaskParamUpdate >::value();
  }
  static const char* value(const ::move_rt::TaskParamUpdateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_rt::TaskParamUpdateResponse> should match 
// service_traits::DataType< ::move_rt::TaskParamUpdate > 
template<>
struct DataType< ::move_rt::TaskParamUpdateResponse>
{
  static const char* value()
  {
    return DataType< ::move_rt::TaskParamUpdate >::value();
  }
  static const char* value(const ::move_rt::TaskParamUpdateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_RT_MESSAGE_TASKPARAMUPDATE_H
