// Generated by gencpp from file move_rt/UpdateFrame.msg
// DO NOT EDIT!


#ifndef MOVE_RT_MESSAGE_UPDATEFRAME_H
#define MOVE_RT_MESSAGE_UPDATEFRAME_H

#include <ros/service_traits.h>


#include <move_rt/UpdateFrameRequest.h>
#include <move_rt/UpdateFrameResponse.h>


namespace move_rt
{

struct UpdateFrame
{

typedef UpdateFrameRequest Request;
typedef UpdateFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateFrame
} // namespace move_rt


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_rt::UpdateFrame > {
  static const char* value()
  {
    return "323fd8a2fa219baecffe89d7ec1e70e3";
  }

  static const char* value(const ::move_rt::UpdateFrame&) { return value(); }
};

template<>
struct DataType< ::move_rt::UpdateFrame > {
  static const char* value()
  {
    return "move_rt/UpdateFrame";
  }

  static const char* value(const ::move_rt::UpdateFrame&) { return value(); }
};


// service_traits::MD5Sum< ::move_rt::UpdateFrameRequest> should match 
// service_traits::MD5Sum< ::move_rt::UpdateFrame > 
template<>
struct MD5Sum< ::move_rt::UpdateFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_rt::UpdateFrame >::value();
  }
  static const char* value(const ::move_rt::UpdateFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_rt::UpdateFrameRequest> should match 
// service_traits::DataType< ::move_rt::UpdateFrame > 
template<>
struct DataType< ::move_rt::UpdateFrameRequest>
{
  static const char* value()
  {
    return DataType< ::move_rt::UpdateFrame >::value();
  }
  static const char* value(const ::move_rt::UpdateFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_rt::UpdateFrameResponse> should match 
// service_traits::MD5Sum< ::move_rt::UpdateFrame > 
template<>
struct MD5Sum< ::move_rt::UpdateFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_rt::UpdateFrame >::value();
  }
  static const char* value(const ::move_rt::UpdateFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_rt::UpdateFrameResponse> should match 
// service_traits::DataType< ::move_rt::UpdateFrame > 
template<>
struct DataType< ::move_rt::UpdateFrameResponse>
{
  static const char* value()
  {
    return DataType< ::move_rt::UpdateFrame >::value();
  }
  static const char* value(const ::move_rt::UpdateFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_RT_MESSAGE_UPDATEFRAME_H
