// Generated by gencpp from file move_rt/UpdateFrameRequest.msg
// DO NOT EDIT!


#ifndef MOVE_RT_MESSAGE_UPDATEFRAMEREQUEST_H
#define MOVE_RT_MESSAGE_UPDATEFRAMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_rt
{
template <class ContainerAllocator>
struct UpdateFrameRequest_
{
  typedef UpdateFrameRequest_<ContainerAllocator> Type;

  UpdateFrameRequest_()
    : frame()  {
    }
  UpdateFrameRequest_(const ContainerAllocator& _alloc)
    : frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_type;
  _frame_type frame;





  typedef boost::shared_ptr< ::move_rt::UpdateFrameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_rt::UpdateFrameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateFrameRequest_

typedef ::move_rt::UpdateFrameRequest_<std::allocator<void> > UpdateFrameRequest;

typedef boost::shared_ptr< ::move_rt::UpdateFrameRequest > UpdateFrameRequestPtr;
typedef boost::shared_ptr< ::move_rt::UpdateFrameRequest const> UpdateFrameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_rt::UpdateFrameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_rt::UpdateFrameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move_rt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'move_rt': ['/home/lar/ros/baxter_ws/devel/share/move_rt/msg', '/home/lar/ros/baxter_ws/devel/share/move_rt/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move_rt::UpdateFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_rt::UpdateFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_rt::UpdateFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_rt::UpdateFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_rt::UpdateFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_rt::UpdateFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_rt::UpdateFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a054304ca480f0e0c67ec5f261591b09";
  }

  static const char* value(const ::move_rt::UpdateFrameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa054304ca480f0e0ULL;
  static const uint64_t static_value2 = 0xc67ec5f261591b09ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_rt::UpdateFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_rt/UpdateFrameRequest";
  }

  static const char* value(const ::move_rt::UpdateFrameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_rt::UpdateFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string frame\n\
";
  }

  static const char* value(const ::move_rt::UpdateFrameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_rt::UpdateFrameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateFrameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_rt::UpdateFrameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_rt::UpdateFrameRequest_<ContainerAllocator>& v)
  {
    s << indent << "frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_RT_MESSAGE_UPDATEFRAMEREQUEST_H
