(cl:defpackage move_rt-srv
  (:use )
  (:export
   "TASKPARAMUPDATE"
   "<TASKPARAMUPDATE-REQUEST>"
   "TASKPARAMUPDATE-REQUEST"
   "<TASKPARAMUPDATE-RESPONSE>"
   "TASKPARAMUPDATE-RESPONSE"
   "UPDATEFRAME"
   "<UPDATEFRAME-REQUEST>"
   "UPDATEFRAME-REQUEST"
   "<UPDATEFRAME-RESPONSE>"
   "UPDATEFRAME-RESPONSE"
  ))

