(cl:defpackage baxter_msgs_mine-msg
  (:use )
  (:export
   "<CAMERADEBUG>"
   "CAMERADEBUG"
   "<GOTOPOINTACTION>"
   "GOTOPOINTACTION"
   "<GOTOPOINTACTIONFEEDBACK>"
   "GOTOPOINTACTIONFEEDBACK"
   "<GOTOPOINTACTIONGOAL>"
   "GOTOPOINTACTIONGOAL"
   "<GOTOPOINTACTIONRESULT>"
   "GOTOPOINTACTIONRESULT"
   "<GOTOPOINTFEEDBACK>"
   "GOTOPOINTFEEDBACK"
   "<GOTOPOINTGOAL>"
   "GOTOPOINTGOAL"
   "<GOTOPOINTRESULT>"
   "GOTOPOINTRESULT"
  ))

