; Auto-generated. Do not edit!


(cl:in-package baxter_msgs_mine-msg)


;//! \htmlinclude GoToPointGoal.msg.html

(cl:defclass <GoToPointGoal> (roslisp-msg-protocol:ros-message)
  ((desired_pose
    :reader desired_pose
    :initarg :desired_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass GoToPointGoal (<GoToPointGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoToPointGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoToPointGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name baxter_msgs_mine-msg:<GoToPointGoal> is deprecated: use baxter_msgs_mine-msg:GoToPointGoal instead.")))

(cl:ensure-generic-function 'desired_pose-val :lambda-list '(m))
(cl:defmethod desired_pose-val ((m <GoToPointGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader baxter_msgs_mine-msg:desired_pose-val is deprecated.  Use baxter_msgs_mine-msg:desired_pose instead.")
  (desired_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoToPointGoal>) ostream)
  "Serializes a message object of type '<GoToPointGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'desired_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoToPointGoal>) istream)
  "Deserializes a message object of type '<GoToPointGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'desired_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoToPointGoal>)))
  "Returns string type for a message object of type '<GoToPointGoal>"
  "baxter_msgs_mine/GoToPointGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoToPointGoal)))
  "Returns string type for a message object of type 'GoToPointGoal"
  "baxter_msgs_mine/GoToPointGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoToPointGoal>)))
  "Returns md5sum for a message object of type '<GoToPointGoal>"
  "0538590fc0be5b737b11f5be6e5b1759")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoToPointGoal)))
  "Returns md5sum for a message object of type 'GoToPointGoal"
  "0538590fc0be5b737b11f5be6e5b1759")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoToPointGoal>)))
  "Returns full string definition for message of type '<GoToPointGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%geometry_msgs/Pose desired_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoToPointGoal)))
  "Returns full string definition for message of type 'GoToPointGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%geometry_msgs/Pose desired_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoToPointGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'desired_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoToPointGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GoToPointGoal
    (cl:cons ':desired_pose (desired_pose msg))
))
