; Auto-generated. Do not edit!


(cl:in-package baxter_msgs_mine-msg)


;//! \htmlinclude GoToPointFeedback.msg.html

(cl:defclass <GoToPointFeedback> (roslisp-msg-protocol:ros-message)
  ((current_pose
    :reader current_pose
    :initarg :current_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass GoToPointFeedback (<GoToPointFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoToPointFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoToPointFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name baxter_msgs_mine-msg:<GoToPointFeedback> is deprecated: use baxter_msgs_mine-msg:GoToPointFeedback instead.")))

(cl:ensure-generic-function 'current_pose-val :lambda-list '(m))
(cl:defmethod current_pose-val ((m <GoToPointFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader baxter_msgs_mine-msg:current_pose-val is deprecated.  Use baxter_msgs_mine-msg:current_pose instead.")
  (current_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoToPointFeedback>) ostream)
  "Serializes a message object of type '<GoToPointFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoToPointFeedback>) istream)
  "Deserializes a message object of type '<GoToPointFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoToPointFeedback>)))
  "Returns string type for a message object of type '<GoToPointFeedback>"
  "baxter_msgs_mine/GoToPointFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoToPointFeedback)))
  "Returns string type for a message object of type 'GoToPointFeedback"
  "baxter_msgs_mine/GoToPointFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoToPointFeedback>)))
  "Returns md5sum for a message object of type '<GoToPointFeedback>"
  "8aa49ba45d5b9d2df8a650fff8d23e31")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoToPointFeedback)))
  "Returns md5sum for a message object of type 'GoToPointFeedback"
  "8aa49ba45d5b9d2df8a650fff8d23e31")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoToPointFeedback>)))
  "Returns full string definition for message of type '<GoToPointFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%geometry_msgs/Pose current_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoToPointFeedback)))
  "Returns full string definition for message of type 'GoToPointFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%geometry_msgs/Pose current_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoToPointFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoToPointFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GoToPointFeedback
    (cl:cons ':current_pose (current_pose msg))
))
