; Auto-generated. Do not edit!


(cl:in-package baxter_msgs_mine-msg)


;//! \htmlinclude GoToJointPosResult.msg.html

(cl:defclass <GoToJointPosResult> (roslisp-msg-protocol:ros-message)
  ((final_pose
    :reader final_pose
    :initarg :final_pose
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass GoToJointPosResult (<GoToJointPosResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoToJointPosResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoToJointPosResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name baxter_msgs_mine-msg:<GoToJointPosResult> is deprecated: use baxter_msgs_mine-msg:GoToJointPosResult instead.")))

(cl:ensure-generic-function 'final_pose-val :lambda-list '(m))
(cl:defmethod final_pose-val ((m <GoToJointPosResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader baxter_msgs_mine-msg:final_pose-val is deprecated.  Use baxter_msgs_mine-msg:final_pose instead.")
  (final_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoToJointPosResult>) ostream)
  "Serializes a message object of type '<GoToJointPosResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'final_pose))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'final_pose))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoToJointPosResult>) istream)
  "Deserializes a message object of type '<GoToJointPosResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'final_pose) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'final_pose)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoToJointPosResult>)))
  "Returns string type for a message object of type '<GoToJointPosResult>"
  "baxter_msgs_mine/GoToJointPosResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoToJointPosResult)))
  "Returns string type for a message object of type 'GoToJointPosResult"
  "baxter_msgs_mine/GoToJointPosResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoToJointPosResult>)))
  "Returns md5sum for a message object of type '<GoToJointPosResult>"
  "7aff8cdaacba4d8354005a6ac587f583")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoToJointPosResult)))
  "Returns md5sum for a message object of type 'GoToJointPosResult"
  "7aff8cdaacba4d8354005a6ac587f583")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoToJointPosResult>)))
  "Returns full string definition for message of type '<GoToJointPosResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float32[] final_pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoToJointPosResult)))
  "Returns full string definition for message of type 'GoToJointPosResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float32[] final_pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoToJointPosResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'final_pose) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoToJointPosResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GoToJointPosResult
    (cl:cons ':final_pose (final_pose msg))
))
