; Auto-generated. Do not edit!


(cl:in-package baxter_msgs_mine-msg)


;//! \htmlinclude GoToJointPosFeedback.msg.html

(cl:defclass <GoToJointPosFeedback> (roslisp-msg-protocol:ros-message)
  ((current_pose
    :reader current_pose
    :initarg :current_pose
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass GoToJointPosFeedback (<GoToJointPosFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoToJointPosFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoToJointPosFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name baxter_msgs_mine-msg:<GoToJointPosFeedback> is deprecated: use baxter_msgs_mine-msg:GoToJointPosFeedback instead.")))

(cl:ensure-generic-function 'current_pose-val :lambda-list '(m))
(cl:defmethod current_pose-val ((m <GoToJointPosFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader baxter_msgs_mine-msg:current_pose-val is deprecated.  Use baxter_msgs_mine-msg:current_pose instead.")
  (current_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoToJointPosFeedback>) ostream)
  "Serializes a message object of type '<GoToJointPosFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'current_pose))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'current_pose))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoToJointPosFeedback>) istream)
  "Deserializes a message object of type '<GoToJointPosFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'current_pose) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'current_pose)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoToJointPosFeedback>)))
  "Returns string type for a message object of type '<GoToJointPosFeedback>"
  "baxter_msgs_mine/GoToJointPosFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoToJointPosFeedback)))
  "Returns string type for a message object of type 'GoToJointPosFeedback"
  "baxter_msgs_mine/GoToJointPosFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoToJointPosFeedback>)))
  "Returns md5sum for a message object of type '<GoToJointPosFeedback>"
  "08f77cad95bf249f1c96e79e0b413d06")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoToJointPosFeedback)))
  "Returns md5sum for a message object of type 'GoToJointPosFeedback"
  "08f77cad95bf249f1c96e79e0b413d06")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoToJointPosFeedback>)))
  "Returns full string definition for message of type '<GoToJointPosFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32[] current_pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoToJointPosFeedback)))
  "Returns full string definition for message of type 'GoToJointPosFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32[] current_pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoToJointPosFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'current_pose) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoToJointPosFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GoToJointPosFeedback
    (cl:cons ':current_pose (current_pose msg))
))
