; Auto-generated. Do not edit!


(cl:in-package process_rope_msgs-srv)


;//! \htmlinclude SampleRope-request.msg.html

(cl:defclass <SampleRope-request> (roslisp-msg-protocol:ros-message)
  ((type
    :reader type
    :initarg :type
    :type cl:integer
    :initform 0)
   (limb
    :reader limb
    :initarg :limb
    :type cl:string
    :initform "")
   (sample_target
    :reader sample_target
    :initarg :sample_target
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SampleRope-request (<SampleRope-request>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SampleRope-request>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SampleRope-request)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name process_rope_msgs-srv:<SampleRope-request> is deprecated: use process_rope_msgs-srv:SampleRope-request instead.")))

(cl:ensure-generic-function 'type-val :lambda-list '(m))
(cl:defmethod type-val ((m <SampleRope-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader process_rope_msgs-srv:type-val is deprecated.  Use process_rope_msgs-srv:type instead.")
  (type m))

(cl:ensure-generic-function 'limb-val :lambda-list '(m))
(cl:defmethod limb-val ((m <SampleRope-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader process_rope_msgs-srv:limb-val is deprecated.  Use process_rope_msgs-srv:limb instead.")
  (limb m))

(cl:ensure-generic-function 'sample_target-val :lambda-list '(m))
(cl:defmethod sample_target-val ((m <SampleRope-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader process_rope_msgs-srv:sample_target-val is deprecated.  Use process_rope_msgs-srv:sample_target instead.")
  (sample_target m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SampleRope-request>) ostream)
  "Serializes a message object of type '<SampleRope-request>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'type)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'limb))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'limb))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'sample_target) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SampleRope-request>) istream)
  "Deserializes a message object of type '<SampleRope-request>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'type)) (cl:read-byte istream))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'limb) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'limb) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:setf (cl:slot-value msg 'sample_target) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SampleRope-request>)))
  "Returns string type for a service object of type '<SampleRope-request>"
  "process_rope_msgs/SampleRopeRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SampleRope-request)))
  "Returns string type for a service object of type 'SampleRope-request"
  "process_rope_msgs/SampleRopeRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SampleRope-request>)))
  "Returns md5sum for a message object of type '<SampleRope-request>"
  "51516dd966b40523ec3a38606b7163ae")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SampleRope-request)))
  "Returns md5sum for a message object of type 'SampleRope-request"
  "51516dd966b40523ec3a38606b7163ae")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SampleRope-request>)))
  "Returns full string definition for message of type '<SampleRope-request>"
  (cl:format cl:nil "char type~%string limb~%bool sample_target~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SampleRope-request)))
  "Returns full string definition for message of type 'SampleRope-request"
  (cl:format cl:nil "char type~%string limb~%bool sample_target~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SampleRope-request>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'limb))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SampleRope-request>))
  "Converts a ROS message object to a list"
  (cl:list 'SampleRope-request
    (cl:cons ':type (type msg))
    (cl:cons ':limb (limb msg))
    (cl:cons ':sample_target (sample_target msg))
))
;//! \htmlinclude SampleRope-response.msg.html

(cl:defclass <SampleRope-response> (roslisp-msg-protocol:ros-message)
  ((sampled_target_points
    :reader sampled_target_points
    :initarg :sampled_target_points
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (sampled_current_points
    :reader sampled_current_points
    :initarg :sampled_current_points
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (pick_points
    :reader pick_points
    :initarg :pick_points
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (pick_img_points
    :reader pick_img_points
    :initarg :pick_img_points
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (place_points
    :reader place_points
    :initarg :place_points
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (place_img_points
    :reader place_img_points
    :initarg :place_img_points
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (h_limb
    :reader h_limb
    :initarg :h_limb
    :type cl:string
    :initform "")
   (success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SampleRope-response (<SampleRope-response>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SampleRope-response>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SampleRope-response)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name process_rope_msgs-srv:<SampleRope-response> is deprecated: use process_rope_msgs-srv:SampleRope-response instead.")))

(cl:ensure-generic-function 'sampled_target_points-val :lambda-list '(m))
(cl:defmethod sampled_target_points-val ((m <SampleRope-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader process_rope_msgs-srv:sampled_target_points-val is deprecated.  Use process_rope_msgs-srv:sampled_target_points instead.")
  (sampled_target_points m))

(cl:ensure-generic-function 'sampled_current_points-val :lambda-list '(m))
(cl:defmethod sampled_current_points-val ((m <SampleRope-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader process_rope_msgs-srv:sampled_current_points-val is deprecated.  Use process_rope_msgs-srv:sampled_current_points instead.")
  (sampled_current_points m))

(cl:ensure-generic-function 'pick_points-val :lambda-list '(m))
(cl:defmethod pick_points-val ((m <SampleRope-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader process_rope_msgs-srv:pick_points-val is deprecated.  Use process_rope_msgs-srv:pick_points instead.")
  (pick_points m))

(cl:ensure-generic-function 'pick_img_points-val :lambda-list '(m))
(cl:defmethod pick_img_points-val ((m <SampleRope-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader process_rope_msgs-srv:pick_img_points-val is deprecated.  Use process_rope_msgs-srv:pick_img_points instead.")
  (pick_img_points m))

(cl:ensure-generic-function 'place_points-val :lambda-list '(m))
(cl:defmethod place_points-val ((m <SampleRope-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader process_rope_msgs-srv:place_points-val is deprecated.  Use process_rope_msgs-srv:place_points instead.")
  (place_points m))

(cl:ensure-generic-function 'place_img_points-val :lambda-list '(m))
(cl:defmethod place_img_points-val ((m <SampleRope-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader process_rope_msgs-srv:place_img_points-val is deprecated.  Use process_rope_msgs-srv:place_img_points instead.")
  (place_img_points m))

(cl:ensure-generic-function 'h_limb-val :lambda-list '(m))
(cl:defmethod h_limb-val ((m <SampleRope-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader process_rope_msgs-srv:h_limb-val is deprecated.  Use process_rope_msgs-srv:h_limb instead.")
  (h_limb m))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <SampleRope-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader process_rope_msgs-srv:success-val is deprecated.  Use process_rope_msgs-srv:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SampleRope-response>) ostream)
  "Serializes a message object of type '<SampleRope-response>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sampled_target_points))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'sampled_target_points))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sampled_current_points))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'sampled_current_points))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'pick_points))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'pick_points))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'pick_img_points))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'pick_img_points))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'place_points))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'place_points))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'place_img_points))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'place_img_points))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'h_limb))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'h_limb))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SampleRope-response>) istream)
  "Deserializes a message object of type '<SampleRope-response>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sampled_target_points) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sampled_target_points)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sampled_current_points) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sampled_current_points)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'pick_points) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'pick_points)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'pick_img_points) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'pick_img_points)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'place_points) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'place_points)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'place_img_points) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'place_img_points)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'h_limb) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'h_limb) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SampleRope-response>)))
  "Returns string type for a service object of type '<SampleRope-response>"
  "process_rope_msgs/SampleRopeResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SampleRope-response)))
  "Returns string type for a service object of type 'SampleRope-response"
  "process_rope_msgs/SampleRopeResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SampleRope-response>)))
  "Returns md5sum for a message object of type '<SampleRope-response>"
  "51516dd966b40523ec3a38606b7163ae")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SampleRope-response)))
  "Returns md5sum for a message object of type 'SampleRope-response"
  "51516dd966b40523ec3a38606b7163ae")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SampleRope-response>)))
  "Returns full string definition for message of type '<SampleRope-response>"
  (cl:format cl:nil "float64[] sampled_target_points~%float64[] sampled_current_points~%float64[] pick_points~%float64[] pick_img_points~%float64[] place_points~%float64[] place_img_points~%string h_limb~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SampleRope-response)))
  "Returns full string definition for message of type 'SampleRope-response"
  (cl:format cl:nil "float64[] sampled_target_points~%float64[] sampled_current_points~%float64[] pick_points~%float64[] pick_img_points~%float64[] place_points~%float64[] place_img_points~%string h_limb~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SampleRope-response>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sampled_target_points) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sampled_current_points) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'pick_points) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'pick_img_points) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'place_points) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'place_img_points) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:length (cl:slot-value msg 'h_limb))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SampleRope-response>))
  "Converts a ROS message object to a list"
  (cl:list 'SampleRope-response
    (cl:cons ':sampled_target_points (sampled_target_points msg))
    (cl:cons ':sampled_current_points (sampled_current_points msg))
    (cl:cons ':pick_points (pick_points msg))
    (cl:cons ':pick_img_points (pick_img_points msg))
    (cl:cons ':place_points (place_points msg))
    (cl:cons ':place_img_points (place_img_points msg))
    (cl:cons ':h_limb (h_limb msg))
    (cl:cons ':success (success msg))
))
(cl:defmethod roslisp-msg-protocol:service-request-type ((msg (cl:eql 'SampleRope)))
  'SampleRope-request)
(cl:defmethod roslisp-msg-protocol:service-response-type ((msg (cl:eql 'SampleRope)))
  'SampleRope-response)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SampleRope)))
  "Returns string type for a service object of type '<SampleRope>"
  "process_rope_msgs/SampleRope")