// Generated by gencpp from file baxter_msgs_mine/CalculateIK.msg
// DO NOT EDIT!


#ifndef BAXTER_MSGS_MINE_MESSAGE_CALCULATEIK_H
#define BAXTER_MSGS_MINE_MESSAGE_CALCULATEIK_H

#include <ros/service_traits.h>


#include <baxter_msgs_mine/CalculateIKRequest.h>
#include <baxter_msgs_mine/CalculateIKResponse.h>


namespace baxter_msgs_mine
{

struct CalculateIK
{

typedef CalculateIKRequest Request;
typedef CalculateIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalculateIK
} // namespace baxter_msgs_mine


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_msgs_mine::CalculateIK > {
  static const char* value()
  {
    return "b26a58bf1f4e5c6080161e53a8d5614f";
  }

  static const char* value(const ::baxter_msgs_mine::CalculateIK&) { return value(); }
};

template<>
struct DataType< ::baxter_msgs_mine::CalculateIK > {
  static const char* value()
  {
    return "baxter_msgs_mine/CalculateIK";
  }

  static const char* value(const ::baxter_msgs_mine::CalculateIK&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_msgs_mine::CalculateIKRequest> should match 
// service_traits::MD5Sum< ::baxter_msgs_mine::CalculateIK > 
template<>
struct MD5Sum< ::baxter_msgs_mine::CalculateIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_msgs_mine::CalculateIK >::value();
  }
  static const char* value(const ::baxter_msgs_mine::CalculateIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_msgs_mine::CalculateIKRequest> should match 
// service_traits::DataType< ::baxter_msgs_mine::CalculateIK > 
template<>
struct DataType< ::baxter_msgs_mine::CalculateIKRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_msgs_mine::CalculateIK >::value();
  }
  static const char* value(const ::baxter_msgs_mine::CalculateIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_msgs_mine::CalculateIKResponse> should match 
// service_traits::MD5Sum< ::baxter_msgs_mine::CalculateIK > 
template<>
struct MD5Sum< ::baxter_msgs_mine::CalculateIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_msgs_mine::CalculateIK >::value();
  }
  static const char* value(const ::baxter_msgs_mine::CalculateIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_msgs_mine::CalculateIKResponse> should match 
// service_traits::DataType< ::baxter_msgs_mine::CalculateIK > 
template<>
struct DataType< ::baxter_msgs_mine::CalculateIKResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_msgs_mine::CalculateIK >::value();
  }
  static const char* value(const ::baxter_msgs_mine::CalculateIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_MSGS_MINE_MESSAGE_CALCULATEIK_H
