// Generated by gencpp from file baxter_msgs_mine/CheckCrossing.msg
// DO NOT EDIT!


#ifndef BAXTER_MSGS_MINE_MESSAGE_CHECKCROSSING_H
#define BAXTER_MSGS_MINE_MESSAGE_CHECKCROSSING_H

#include <ros/service_traits.h>


#include <baxter_msgs_mine/CheckCrossingRequest.h>
#include <baxter_msgs_mine/CheckCrossingResponse.h>


namespace baxter_msgs_mine
{

struct CheckCrossing
{

typedef CheckCrossingRequest Request;
typedef CheckCrossingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckCrossing
} // namespace baxter_msgs_mine


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_msgs_mine::CheckCrossing > {
  static const char* value()
  {
    return "43681e71f21e5675de1d59f1aa7c14d7";
  }

  static const char* value(const ::baxter_msgs_mine::CheckCrossing&) { return value(); }
};

template<>
struct DataType< ::baxter_msgs_mine::CheckCrossing > {
  static const char* value()
  {
    return "baxter_msgs_mine/CheckCrossing";
  }

  static const char* value(const ::baxter_msgs_mine::CheckCrossing&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_msgs_mine::CheckCrossingRequest> should match 
// service_traits::MD5Sum< ::baxter_msgs_mine::CheckCrossing > 
template<>
struct MD5Sum< ::baxter_msgs_mine::CheckCrossingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_msgs_mine::CheckCrossing >::value();
  }
  static const char* value(const ::baxter_msgs_mine::CheckCrossingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_msgs_mine::CheckCrossingRequest> should match 
// service_traits::DataType< ::baxter_msgs_mine::CheckCrossing > 
template<>
struct DataType< ::baxter_msgs_mine::CheckCrossingRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_msgs_mine::CheckCrossing >::value();
  }
  static const char* value(const ::baxter_msgs_mine::CheckCrossingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_msgs_mine::CheckCrossingResponse> should match 
// service_traits::MD5Sum< ::baxter_msgs_mine::CheckCrossing > 
template<>
struct MD5Sum< ::baxter_msgs_mine::CheckCrossingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_msgs_mine::CheckCrossing >::value();
  }
  static const char* value(const ::baxter_msgs_mine::CheckCrossingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_msgs_mine::CheckCrossingResponse> should match 
// service_traits::DataType< ::baxter_msgs_mine::CheckCrossing > 
template<>
struct DataType< ::baxter_msgs_mine::CheckCrossingResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_msgs_mine::CheckCrossing >::value();
  }
  static const char* value(const ::baxter_msgs_mine::CheckCrossingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_MSGS_MINE_MESSAGE_CHECKCROSSING_H
