// Generated by gencpp from file baxter_msgs_mine/Cvt2Wrld.msg
// DO NOT EDIT!


#ifndef BAXTER_MSGS_MINE_MESSAGE_CVT2WRLD_H
#define BAXTER_MSGS_MINE_MESSAGE_CVT2WRLD_H

#include <ros/service_traits.h>


#include <baxter_msgs_mine/Cvt2WrldRequest.h>
#include <baxter_msgs_mine/Cvt2WrldResponse.h>


namespace baxter_msgs_mine
{

struct Cvt2Wrld
{

typedef Cvt2WrldRequest Request;
typedef Cvt2WrldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Cvt2Wrld
} // namespace baxter_msgs_mine


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_msgs_mine::Cvt2Wrld > {
  static const char* value()
  {
    return "2ce5c3384f15a765a1063a3a6f79f77c";
  }

  static const char* value(const ::baxter_msgs_mine::Cvt2Wrld&) { return value(); }
};

template<>
struct DataType< ::baxter_msgs_mine::Cvt2Wrld > {
  static const char* value()
  {
    return "baxter_msgs_mine/Cvt2Wrld";
  }

  static const char* value(const ::baxter_msgs_mine::Cvt2Wrld&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_msgs_mine::Cvt2WrldRequest> should match 
// service_traits::MD5Sum< ::baxter_msgs_mine::Cvt2Wrld > 
template<>
struct MD5Sum< ::baxter_msgs_mine::Cvt2WrldRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_msgs_mine::Cvt2Wrld >::value();
  }
  static const char* value(const ::baxter_msgs_mine::Cvt2WrldRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_msgs_mine::Cvt2WrldRequest> should match 
// service_traits::DataType< ::baxter_msgs_mine::Cvt2Wrld > 
template<>
struct DataType< ::baxter_msgs_mine::Cvt2WrldRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_msgs_mine::Cvt2Wrld >::value();
  }
  static const char* value(const ::baxter_msgs_mine::Cvt2WrldRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_msgs_mine::Cvt2WrldResponse> should match 
// service_traits::MD5Sum< ::baxter_msgs_mine::Cvt2Wrld > 
template<>
struct MD5Sum< ::baxter_msgs_mine::Cvt2WrldResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_msgs_mine::Cvt2Wrld >::value();
  }
  static const char* value(const ::baxter_msgs_mine::Cvt2WrldResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_msgs_mine::Cvt2WrldResponse> should match 
// service_traits::DataType< ::baxter_msgs_mine::Cvt2Wrld > 
template<>
struct DataType< ::baxter_msgs_mine::Cvt2WrldResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_msgs_mine::Cvt2Wrld >::value();
  }
  static const char* value(const ::baxter_msgs_mine::Cvt2WrldResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_MSGS_MINE_MESSAGE_CVT2WRLD_H
