// Generated by gencpp from file baxter_msgs_mine/Cvt2WrldRequest.msg
// DO NOT EDIT!


#ifndef BAXTER_MSGS_MINE_MESSAGE_CVT2WRLDREQUEST_H
#define BAXTER_MSGS_MINE_MESSAGE_CVT2WRLDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_msgs_mine
{
template <class ContainerAllocator>
struct Cvt2WrldRequest_
{
  typedef Cvt2WrldRequest_<ContainerAllocator> Type;

  Cvt2WrldRequest_()
    : img_points()
    , limb()  {
    }
  Cvt2WrldRequest_(const ContainerAllocator& _alloc)
    : img_points(_alloc)
    , limb(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _img_points_type;
  _img_points_type img_points;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _limb_type;
  _limb_type limb;





  typedef boost::shared_ptr< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Cvt2WrldRequest_

typedef ::baxter_msgs_mine::Cvt2WrldRequest_<std::allocator<void> > Cvt2WrldRequest;

typedef boost::shared_ptr< ::baxter_msgs_mine::Cvt2WrldRequest > Cvt2WrldRequestPtr;
typedef boost::shared_ptr< ::baxter_msgs_mine::Cvt2WrldRequest const> Cvt2WrldRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_msgs_mine

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'baxter_msgs_mine': ['/home/lar/ros/test_ws/src/baxter_msgs_mine/msg', '/home/lar/ros/test_ws/devel/share/baxter_msgs_mine/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a507a4e10034cb4292c21ac6c41ea05";
  }

  static const char* value(const ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a507a4e10034cb4ULL;
  static const uint64_t static_value2 = 0x292c21ac6c41ea05ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_msgs_mine/Cvt2WrldRequest";
  }

  static const char* value(const ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] img_points\n\
string limb\n\
";
  }

  static const char* value(const ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.img_points);
      stream.next(m.limb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cvt2WrldRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_msgs_mine::Cvt2WrldRequest_<ContainerAllocator>& v)
  {
    s << indent << "img_points[]" << std::endl;
    for (size_t i = 0; i < v.img_points.size(); ++i)
    {
      s << indent << "  img_points[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.img_points[i]);
    }
    s << indent << "limb: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.limb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_MSGS_MINE_MESSAGE_CVT2WRLDREQUEST_H
