// Generated by gencpp from file baxter_msgs_mine/Cvt2WrldResponse.msg
// DO NOT EDIT!


#ifndef BAXTER_MSGS_MINE_MESSAGE_CVT2WRLDRESPONSE_H
#define BAXTER_MSGS_MINE_MESSAGE_CVT2WRLDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_msgs_mine
{
template <class ContainerAllocator>
struct Cvt2WrldResponse_
{
  typedef Cvt2WrldResponse_<ContainerAllocator> Type;

  Cvt2WrldResponse_()
    : wrld_points()
    , success(false)  {
    }
  Cvt2WrldResponse_(const ContainerAllocator& _alloc)
    : wrld_points(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _wrld_points_type;
  _wrld_points_type wrld_points;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Cvt2WrldResponse_

typedef ::baxter_msgs_mine::Cvt2WrldResponse_<std::allocator<void> > Cvt2WrldResponse;

typedef boost::shared_ptr< ::baxter_msgs_mine::Cvt2WrldResponse > Cvt2WrldResponsePtr;
typedef boost::shared_ptr< ::baxter_msgs_mine::Cvt2WrldResponse const> Cvt2WrldResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_msgs_mine

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'baxter_msgs_mine': ['/home/lar/ros/test_ws/src/baxter_msgs_mine/msg', '/home/lar/ros/test_ws/devel/share/baxter_msgs_mine/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9dff662a22b591e99b2ddc14401c766b";
  }

  static const char* value(const ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9dff662a22b591e9ULL;
  static const uint64_t static_value2 = 0x9b2ddc14401c766bULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_msgs_mine/Cvt2WrldResponse";
  }

  static const char* value(const ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] wrld_points\n\
bool success\n\
";
  }

  static const char* value(const ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wrld_points);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cvt2WrldResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_msgs_mine::Cvt2WrldResponse_<ContainerAllocator>& v)
  {
    s << indent << "wrld_points[]" << std::endl;
    for (size_t i = 0; i < v.wrld_points.size(); ++i)
    {
      s << indent << "  wrld_points[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.wrld_points[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_MSGS_MINE_MESSAGE_CVT2WRLDRESPONSE_H
