// Generated by gencpp from file baxter_msgs_mine/GoToJointGoal.msg
// DO NOT EDIT!


#ifndef BAXTER_MSGS_MINE_MESSAGE_GOTOJOINTGOAL_H
#define BAXTER_MSGS_MINE_MESSAGE_GOTOJOINTGOAL_H

#include <ros/service_traits.h>


#include <baxter_msgs_mine/GoToJointGoalRequest.h>
#include <baxter_msgs_mine/GoToJointGoalResponse.h>


namespace baxter_msgs_mine
{

struct GoToJointGoal
{

typedef GoToJointGoalRequest Request;
typedef GoToJointGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToJointGoal
} // namespace baxter_msgs_mine


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_msgs_mine::GoToJointGoal > {
  static const char* value()
  {
    return "aeb0d7ee84568d74897d5eaf2fae4da6";
  }

  static const char* value(const ::baxter_msgs_mine::GoToJointGoal&) { return value(); }
};

template<>
struct DataType< ::baxter_msgs_mine::GoToJointGoal > {
  static const char* value()
  {
    return "baxter_msgs_mine/GoToJointGoal";
  }

  static const char* value(const ::baxter_msgs_mine::GoToJointGoal&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_msgs_mine::GoToJointGoalRequest> should match 
// service_traits::MD5Sum< ::baxter_msgs_mine::GoToJointGoal > 
template<>
struct MD5Sum< ::baxter_msgs_mine::GoToJointGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_msgs_mine::GoToJointGoal >::value();
  }
  static const char* value(const ::baxter_msgs_mine::GoToJointGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_msgs_mine::GoToJointGoalRequest> should match 
// service_traits::DataType< ::baxter_msgs_mine::GoToJointGoal > 
template<>
struct DataType< ::baxter_msgs_mine::GoToJointGoalRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_msgs_mine::GoToJointGoal >::value();
  }
  static const char* value(const ::baxter_msgs_mine::GoToJointGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_msgs_mine::GoToJointGoalResponse> should match 
// service_traits::MD5Sum< ::baxter_msgs_mine::GoToJointGoal > 
template<>
struct MD5Sum< ::baxter_msgs_mine::GoToJointGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_msgs_mine::GoToJointGoal >::value();
  }
  static const char* value(const ::baxter_msgs_mine::GoToJointGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_msgs_mine::GoToJointGoalResponse> should match 
// service_traits::DataType< ::baxter_msgs_mine::GoToJointGoal > 
template<>
struct DataType< ::baxter_msgs_mine::GoToJointGoalResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_msgs_mine::GoToJointGoal >::value();
  }
  static const char* value(const ::baxter_msgs_mine::GoToJointGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_MSGS_MINE_MESSAGE_GOTOJOINTGOAL_H
