// Generated by gencpp from file baxter_msgs_mine/ImagePoints.msg
// DO NOT EDIT!


#ifndef BAXTER_MSGS_MINE_MESSAGE_IMAGEPOINTS_H
#define BAXTER_MSGS_MINE_MESSAGE_IMAGEPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_msgs_mine
{
template <class ContainerAllocator>
struct ImagePoints_
{
  typedef ImagePoints_<ContainerAllocator> Type;

  ImagePoints_()
    : sampled_target_points()
    , sampled_current_points()
    , hold_point_coords()
    , pick_point_coords()
    , place_point_coords()  {
    }
  ImagePoints_(const ContainerAllocator& _alloc)
    : sampled_target_points(_alloc)
    , sampled_current_points(_alloc)
    , hold_point_coords(_alloc)
    , pick_point_coords(_alloc)
    , place_point_coords(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sampled_target_points_type;
  _sampled_target_points_type sampled_target_points;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sampled_current_points_type;
  _sampled_current_points_type sampled_current_points;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _hold_point_coords_type;
  _hold_point_coords_type hold_point_coords;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pick_point_coords_type;
  _pick_point_coords_type pick_point_coords;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _place_point_coords_type;
  _place_point_coords_type place_point_coords;





  typedef boost::shared_ptr< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> const> ConstPtr;

}; // struct ImagePoints_

typedef ::baxter_msgs_mine::ImagePoints_<std::allocator<void> > ImagePoints;

typedef boost::shared_ptr< ::baxter_msgs_mine::ImagePoints > ImagePointsPtr;
typedef boost::shared_ptr< ::baxter_msgs_mine::ImagePoints const> ImagePointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_msgs_mine

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'baxter_msgs_mine': ['/home/lar/ros/test_ws/src/baxter_msgs_mine/msg', '/home/lar/ros/test_ws/devel/share/baxter_msgs_mine/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d42c80547db6a939e881199410cfe736";
  }

  static const char* value(const ::baxter_msgs_mine::ImagePoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd42c80547db6a939ULL;
  static const uint64_t static_value2 = 0xe881199410cfe736ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_msgs_mine/ImagePoints";
  }

  static const char* value(const ::baxter_msgs_mine::ImagePoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] sampled_target_points\n\
float64[] sampled_current_points\n\
float64[] hold_point_coords\n\
float64[] pick_point_coords\n\
float64[] place_point_coords\n\
";
  }

  static const char* value(const ::baxter_msgs_mine::ImagePoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sampled_target_points);
      stream.next(m.sampled_current_points);
      stream.next(m.hold_point_coords);
      stream.next(m.pick_point_coords);
      stream.next(m.place_point_coords);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImagePoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_msgs_mine::ImagePoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_msgs_mine::ImagePoints_<ContainerAllocator>& v)
  {
    s << indent << "sampled_target_points[]" << std::endl;
    for (size_t i = 0; i < v.sampled_target_points.size(); ++i)
    {
      s << indent << "  sampled_target_points[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sampled_target_points[i]);
    }
    s << indent << "sampled_current_points[]" << std::endl;
    for (size_t i = 0; i < v.sampled_current_points.size(); ++i)
    {
      s << indent << "  sampled_current_points[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sampled_current_points[i]);
    }
    s << indent << "hold_point_coords[]" << std::endl;
    for (size_t i = 0; i < v.hold_point_coords.size(); ++i)
    {
      s << indent << "  hold_point_coords[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.hold_point_coords[i]);
    }
    s << indent << "pick_point_coords[]" << std::endl;
    for (size_t i = 0; i < v.pick_point_coords.size(); ++i)
    {
      s << indent << "  pick_point_coords[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pick_point_coords[i]);
    }
    s << indent << "place_point_coords[]" << std::endl;
    for (size_t i = 0; i < v.place_point_coords.size(); ++i)
    {
      s << indent << "  place_point_coords[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.place_point_coords[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_MSGS_MINE_MESSAGE_IMAGEPOINTS_H
