// Generated by gencpp from file baxter_msgs_mine/PositionCommandMine.msg
// DO NOT EDIT!


#ifndef BAXTER_MSGS_MINE_MESSAGE_POSITIONCOMMANDMINE_H
#define BAXTER_MSGS_MINE_MESSAGE_POSITIONCOMMANDMINE_H

#include <ros/service_traits.h>


#include <baxter_msgs_mine/PositionCommandMineRequest.h>
#include <baxter_msgs_mine/PositionCommandMineResponse.h>


namespace baxter_msgs_mine
{

struct PositionCommandMine
{

typedef PositionCommandMineRequest Request;
typedef PositionCommandMineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositionCommandMine
} // namespace baxter_msgs_mine


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_msgs_mine::PositionCommandMine > {
  static const char* value()
  {
    return "90005b3bd3e0858473cd0f1bcad7b688";
  }

  static const char* value(const ::baxter_msgs_mine::PositionCommandMine&) { return value(); }
};

template<>
struct DataType< ::baxter_msgs_mine::PositionCommandMine > {
  static const char* value()
  {
    return "baxter_msgs_mine/PositionCommandMine";
  }

  static const char* value(const ::baxter_msgs_mine::PositionCommandMine&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_msgs_mine::PositionCommandMineRequest> should match 
// service_traits::MD5Sum< ::baxter_msgs_mine::PositionCommandMine > 
template<>
struct MD5Sum< ::baxter_msgs_mine::PositionCommandMineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_msgs_mine::PositionCommandMine >::value();
  }
  static const char* value(const ::baxter_msgs_mine::PositionCommandMineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_msgs_mine::PositionCommandMineRequest> should match 
// service_traits::DataType< ::baxter_msgs_mine::PositionCommandMine > 
template<>
struct DataType< ::baxter_msgs_mine::PositionCommandMineRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_msgs_mine::PositionCommandMine >::value();
  }
  static const char* value(const ::baxter_msgs_mine::PositionCommandMineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_msgs_mine::PositionCommandMineResponse> should match 
// service_traits::MD5Sum< ::baxter_msgs_mine::PositionCommandMine > 
template<>
struct MD5Sum< ::baxter_msgs_mine::PositionCommandMineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_msgs_mine::PositionCommandMine >::value();
  }
  static const char* value(const ::baxter_msgs_mine::PositionCommandMineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_msgs_mine::PositionCommandMineResponse> should match 
// service_traits::DataType< ::baxter_msgs_mine::PositionCommandMine > 
template<>
struct DataType< ::baxter_msgs_mine::PositionCommandMineResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_msgs_mine::PositionCommandMine >::value();
  }
  static const char* value(const ::baxter_msgs_mine::PositionCommandMineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_MSGS_MINE_MESSAGE_POSITIONCOMMANDMINE_H
