// Generated by gencpp from file baxter_msgs_mine/ProcessImageResponse.msg
// DO NOT EDIT!


#ifndef BAXTER_MSGS_MINE_MESSAGE_PROCESSIMAGERESPONSE_H
#define BAXTER_MSGS_MINE_MESSAGE_PROCESSIMAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_msgs_mine
{
template <class ContainerAllocator>
struct ProcessImageResponse_
{
  typedef ProcessImageResponse_<ContainerAllocator> Type;

  ProcessImageResponse_()
    : extracted_features()
    , success(false)  {
    }
  ProcessImageResponse_(const ContainerAllocator& _alloc)
    : extracted_features(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _extracted_features_type;
  _extracted_features_type extracted_features;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ProcessImageResponse_

typedef ::baxter_msgs_mine::ProcessImageResponse_<std::allocator<void> > ProcessImageResponse;

typedef boost::shared_ptr< ::baxter_msgs_mine::ProcessImageResponse > ProcessImageResponsePtr;
typedef boost::shared_ptr< ::baxter_msgs_mine::ProcessImageResponse const> ProcessImageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_msgs_mine

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'baxter_msgs_mine': ['/home/lar/ros/test_ws/devel/share/baxter_msgs_mine/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ce4ca47f8921cc12e7516aac3def722";
  }

  static const char* value(const ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ce4ca47f8921cc1ULL;
  static const uint64_t static_value2 = 0x2e7516aac3def722ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_msgs_mine/ProcessImageResponse";
  }

  static const char* value(const ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] extracted_features\n\
bool success\n\
";
  }

  static const char* value(const ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.extracted_features);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProcessImageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_msgs_mine::ProcessImageResponse_<ContainerAllocator>& v)
  {
    s << indent << "extracted_features[]" << std::endl;
    for (size_t i = 0; i < v.extracted_features.size(); ++i)
    {
      s << indent << "  extracted_features[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.extracted_features[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_MSGS_MINE_MESSAGE_PROCESSIMAGERESPONSE_H
