(cl:defpackage baxter_msgs_mine-srv
  (:use )
  (:export
   "CALCULATEIK"
   "<CALCULATEIK-REQUEST>"
   "CALCULATEIK-REQUEST"
   "<CALCULATEIK-RESPONSE>"
   "CALCULATEIK-RESPONSE"
   "POSITIONCOMMANDMINE"
   "<POSITIONCOMMANDMINE-REQUEST>"
   "POSITIONCOMMANDMINE-REQUEST"
   "<POSITIONCOMMANDMINE-RESPONSE>"
   "POSITIONCOMMANDMINE-RESPONSE"
   "PROCESSIMAGE"
   "<PROCESSIMAGE-REQUEST>"
   "PROCESSIMAGE-REQUEST"
   "<PROCESSIMAGE-RESPONSE>"
   "PROCESSIMAGE-RESPONSE"
  ))

